ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS processor text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ram text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS storage text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS screen text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gpu text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS battery text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS os text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS connectivity text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS weight text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS condition text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS color text NOT NULL DEFAULT '';